### ISSUE TITLE
Dotenv may not be loaded in time for loading of config/database.yml

### ISSUE THREAD

**Issue by technicalpickles** [bkeepers/dotenv#19]
I've been using dotenv in more places recently, but one place that I'm having problems with right now is in config/database.yml on a staging server (ie non dev environment):

```
staging:
  adapter: postgresql
  database: <%= ENV['POSTGRESQL_DATABASE'] %>
  host: <%= ENV['POSTGRESQL_HOST'] %>
  username: <%= ENV['POSTGRESQL_USERNAME'] %>
  password: <%= ENV['POSTGRESQL_PASSWORD'] %>
  pool: <%= ENV['POSTGRESQL_POOL'] || 5 %>
  timeout: <%= ENV['POSTGRESQL_TIMEOUT'] || 5000 %>
```

I was having a heck of a time, because these ended up being empty, which means it tries loading on the localhost rather than a different server. I added debugging raises like this:

```
  database: <%= ENV['POSTGRESQL_DATABASE'] || raise no "ENV['POSTGRESQL_DATABASE'] " %>
```

And sure enough, it's raised. I also threw in a `<%= raise ENV.inspect %>`, and none of the variables in .env or .env.staging are loaded. I thought that was weird, because I have used something like this without problem in development when using boxen:

```
development:
  adapter: mysql2
  database: app_development
  username: root
  password:
  port: <%= ENV['BOXEN_MYSQL_PORT'] || 3306 %>
```

My current hunch is that ActiveRecord::Railtie is being much earlier in the initialization process than dotenv is. I'll report back if I'm able to debug this anymore.
