### ISSUE TITLE
Muiltiline ENV vars not properly parsed

### ISSUE THREAD

**Issue by etcook** [bkeepers/dotenv#357]
### Steps to reproduce
storage.yml
```yaml
google:
  service: GCS
  project: <%= ENV['GCS_PROJECT'] %>
  bucket: <%= ENV['GCS_BUCKET'] %>
  credentials:
    type: "service_account"
    project_id: <%= ENV['GCS_PROJECT_ID'] %>
    private_key_id: <%= ENV['GCS_PRIVATE_KEY_ID'] %>
    private_key: <%= ENV['GCS_PRIVATE_KEY'] %>
    client_email: <%= ENV['GCS_CLIENT_EMAIL'] %>
    client_id: <%= ENV['GCS_CLIENT_ID'] %>
    auth_uri: "https://accounts.google.com/o/oauth2/auth"
    token_uri: "https://accounts.google.com/o/oauth2/token"
    auth_provider_x509_cert_url: "https://www.googleapis.com/oauth2/v1/certs"
    client_x509_cert_url: <%= ENV['GCS_CLIENT_X509_CERT_URL'] %>
```

.env
```env
GCS_PRIVATE_KEY="-----BEGIN PRIVATE KEY-----\nMIIEvgIB..vypo\n-----END PRIVATE KEY-----\n"
```

### Expected behavior
Env var should be parsed and properly 

### Actual behavior
YAML syntax error occurred while parsing /app/config/storage.yml. Please note that YAML must be consistently indented using spaces. Tabs are not allowed. Error: (<unknown>): could not find expected ':' while scanning a simple key at line 33 column 1 (RuntimeError)

If I paste the string directly into the storage.yml, it interprets without issue.

### System configuration
Used both gem v2.5 as well as pulled directly from master so I could use require_keys to ensure var was loaded.

**Rails version**:
5.2

**Ruby version**:
2.4.4
