### ISSUE TITLE
Use ERB in env file?

### ISSUE THREAD

**Issue by benlieb** [bkeepers/dotenv#501]
Is there any way to parse this first with ERB (using Rails)?

Similar to how yml files work:

```yml
  url: <%= ApplicationConfig.defaults("REDIS_URL") %>
  channel_prefix: threadable_api_production

```

**Comment by gcentauri** [comment]
i've been using `yml` files with `config_for(:the_thing)` to get the ENV files into rails

```
# config/the_thing.yml
shared:
  base_url: <%= ENV["BASE_URL"] %>
  admin_password: <%= ENV["ADMIN_PASSWORD"] %>
```

does this get you what you need? rather than trying to run ruby and interpolate in the `.env` file
